In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
weather_df = pd.read_csv('Jan2023_Nairobi_weather_data.csv')
weather_df.head()

,Time,Temperature (°F),Unnamed: 2,Unnamed: 3,Dew Point (°F),Unnamed: 5,Unnamed: 6,Humidity (%),Unnamed: 8,Unnamed: 9,Wind Speed (mph),Unnamed: 11,Unnamed: 12,Pressure (in),Unnamed: 14,Unnamed: 15,Precipitation (in)
0,Jan,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Total
1,1,79,68.5,59,55,51.1,45,77,55.6,32,23,9.5,0,24.7,24.6,24.5,0
2,2,73,65.5,59,55,53.4,50,82,65.9,44,23,10.2,0,24.6,24.6,24.6,0
3,3,72,65.3,61,59,57.1,54,94,75.8,60,24,13.3,0,24.6,24.6,24.6,0
4,4,70,64.2,61,59,57.5,54,94,80,56,17,10.5,0,24.6,24.6,24.6,0

In [4]:
weather_df

,Time,Temperature (°F),Unnamed: 2,Unnamed: 3,Dew Point (°F),Unnamed: 5,Unnamed: 6,Humidity (%),Unnamed: 8,Unnamed: 9,Wind Speed (mph),Unnamed: 11,Unnamed: 12,Pressure (in),Unnamed: 14,Unnamed: 15,Precipitation (in)
0,Jan,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Total
1,1,79,68.5,59,55,51.1,45,77,55.6,32,23,9.5,0,24.7,24.6,24.5,0
2,2,73,65.5,59,55,53.4,50,82,65.9,44,23,10.2,0,24.6,24.6,24.6,0
3,3,72,65.3,61,59,57.1,54,94,75.8,60,24,13.3,0,24.6,24.6,24.6,0
4,4,70,64.2,61,59,57.5,54,94,80,56,17,10.5,0,24.6,24.6,24.6,0
5,5,75,65.5,59,57,52.1,46,94,64.8,38,20,9.3,0,24.6,24.6,24.6,0
6,6,79,68.5,54,54,47.4,45,82,49.9,30,17,7.6,0,24.6,24.6,24.5,0
7,7,79,68.8,57,54,50,46,82,53.9,34,24,9.1,0,24.6,24.6,24.5,0
8,8,81,69.8,61,57,54,50,77,58.8,34,21,8.7,0,24.6,24.6,24.5,0
9,9,79,68.9,61,59,56.1,52,94,66.3,39,18,8.3,0,24.6,24.6,24.5,0
10,10,77,69,61,59,54.8,50,94,63.3,39,17,8.8,0,24.7,24.6,24.6,0
11,11,79,69.5,61,57,54.4,50,88,60.8,39,24,13,0,24.6,24.6,24.5,0
12,12,81,70.1,61,55,53.3,46,82,57.5,32,21,9.3,0,24.6,24.6,24.5,0
13,13,81,69.2,57,59,50.8,39,94,56.6,24,17,7.7,0,24.6,24.6,24.5,0
14,14,79,69.5,61,52,47.2,39,68,47,26,23,8.3,0,24.6,24.6,24.5,0
15,15,79,68.8,57,50,47.8,45,72,49.3,30,23,8.3,0,24.6,24.6,24.5,0
16,16,81,69,57,52,48.5,43,77,50.1,26,23,9.5,0,24.6,24.6,24.5,0
17,17,79,68.5,57,57,51,41,88,57.7,26,23,8.6,0,24.6,24.6,24.5,0
18,18,84,71.5,55,57,43.3,30,88,43,14,23,8.1,0,24.6,24.6,24.5,0
19,19,82,71.9,59,50,44.7,37,63,40.4,20,14,6.6,0,24.6,24.6,24.5,0
20,20,82,71.5,61,57,51.6,45,88,52.5,28,21,8,0,24.6,24.5,24.4,0
21,21,81,70.8,59,57,50.1,45,88,51.6,28,23,10.6,0,24.6,24.5,24.4,0
22,22,77,68.1,57,54,49.2,45,72,52.3,34,21,7.9,0,24.6,24.5,24.5,0
23,23,79,69.6,63,57,53.5,50,82,57.9,36,18,7.7,0,24.6,24.5,24.5,0
24,24,79,68.9,59,59,52.6,45,94,59.7,34,17,7.8,0,24.6,24.6,24.5,0
25,25,82,71,61,54,48.8,41,77,48.3,23,21,7.7,0,24.6,24.5,24.5,0
26,26,84,71,59,52,44.1,30,72,43.6,16,21,7.9,0,24.6,24.5,24.5,0
27,27,79,70.7,59,52,47.3,41,67,44.5,26,21,9.7,0,24.6,24.5,24.5,0
28,28,81,63.5,0,55,43.2,0,82,45.1,0,23,9.7,0,24.6,24.5,24.5,0
29,29,82,70.6,59,52,45.5,39,72,44.1,21,23,8.1,0,24.6,24.5,24.5,0
30,30,82,70.7,55,50,46.5,41,77,45,26,23,7.1,0,24.6,24.6,24.5,0
31,31,82,71.9,61,54,48,41,72,45.7,24,18,8.9,0,24.6,24.6,24.5,0

In [5]:
weather_df.dtypes

Time                  object
Temperature (°F)      object
Unnamed: 2            object
Unnamed: 3            object
Dew Point (°F)        object
Unnamed: 5            object
Unnamed: 6            object
Humidity (%)          object
Unnamed: 8            object
Unnamed: 9            object
Wind Speed (mph)      object
Unnamed: 11           object
Unnamed: 12           object
Pressure (in)         object
Unnamed: 14           object
Unnamed: 15           object
Precipitation (in)    object
dtype: object

In [7]:
weather_df.set_index('Time', inplace=True)

In [8]:
weather_df

,Temperature (°F),Unnamed: 2,Unnamed: 3,Dew Point (°F),Unnamed: 5,Unnamed: 6,Humidity (%),Unnamed: 8,Unnamed: 9,Wind Speed (mph),Unnamed: 11,Unnamed: 12,Pressure (in),Unnamed: 14,Unnamed: 15,Precipitation (in)
Time,,,,,,,,,,,,,,,,
Jan,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Max,Avg,Min,Total
1,79,68.5,59,55,51.1,45,77,55.6,32,23,9.5,0,24.7,24.6,24.5,0
2,73,65.5,59,55,53.4,50,82,65.9,44,23,10.2,0,24.6,24.6,24.6,0
3,72,65.3,61,59,57.1,54,94,75.8,60,24,13.3,0,24.6,24.6,24.6,0
4,70,64.2,61,59,57.5,54,94,80,56,17,10.5,0,24.6,24.6,24.6,0
5,75,65.5,59,57,52.1,46,94,64.8,38,20,9.3,0,24.6,24.6,24.6,0
6,79,68.5,54,54,47.4,45,82,49.9,30,17,7.6,0,24.6,24.6,24.5,0
7,79,68.8,57,54,50,46,82,53.9,34,24,9.1,0,24.6,24.6,24.5,0
8,81,69.8,61,57,54,50,77,58.8,34,21,8.7,0,24.6,24.6,24.5,0
9,79,68.9,61,59,56.1,52,94,66.3,39,18,8.3,0,24.6,24.6,24.5,0
10,77,69,61,59,54.8,50,94,63.3,39,17,8.8,0,24.7,24.6,24.6,0
11,79,69.5,61,57,54.4,50,88,60.8,39,24,13,0,24.6,24.6,24.5,0
12,81,70.1,61,55,53.3,46,82,57.5,32,21,9.3,0,24.6,24.6,24.5,0
13,81,69.2,57,59,50.8,39,94,56.6,24,17,7.7,0,24.6,24.6,24.5,0
14,79,69.5,61,52,47.2,39,68,47,26,23,8.3,0,24.6,24.6,24.5,0
15,79,68.8,57,50,47.8,45,72,49.3,30,23,8.3,0,24.6,24.6,24.5,0
16,81,69,57,52,48.5,43,77,50.1,26,23,9.5,0,24.6,24.6,24.5,0
17,79,68.5,57,57,51,41,88,57.7,26,23,8.6,0,24.6,24.6,24.5,0
18,84,71.5,55,57,43.3,30,88,43,14,23,8.1,0,24.6,24.6,24.5,0
19,82,71.9,59,50,44.7,37,63,40.4,20,14,6.6,0,24.6,24.6,24.5,0
20,82,71.5,61,57,51.6,45,88,52.5,28,21,8,0,24.6,24.5,24.4,0
21,81,70.8,59,57,50.1,45,88,51.6,28,23,10.6,0,24.6,24.5,24.4,0
22,77,68.1,57,54,49.2,45,72,52.3,34,21,7.9,0,24.6,24.5,24.5,0
23,79,69.6,63,57,53.5,50,82,57.9,36,18,7.7,0,24.6,24.5,24.5,0
24,79,68.9,59,59,52.6,45,94,59.7,34,17,7.8,0,24.6,24.6,24.5,0
25,82,71,61,54,48.8,41,77,48.3,23,21,7.7,0,24.6,24.5,24.5,0
26,84,71,59,52,44.1,30,72,43.6,16,21,7.9,0,24.6,24.5,24.5,0
27,79,70.7,59,52,47.3,41,67,44.5,26,21,9.7,0,24.6,24.5,24.5,0
28,81,63.5,0,55,43.2,0,82,45.1,0,23,9.7,0,24.6,24.5,24.5,0
29,82,70.6,59,52,45.5,39,72,44.1,21,23,8.1,0,24.6,24.5,24.5,0
30,82,70.7,55,50,46.5,41,77,45,26,23,7.1,0,24.6,24.6,24.5,0
31,82,71.9,61,54,48,41,72,45.7,24,18,8.9,0,24.6,24.6,24.5,0